# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.8/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.8/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zarawasique/projects/PokemonCatalogue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zarawasique/projects/PokemonCatalogue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.8/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.8/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zarawasique/projects/PokemonCatalogue/CMakeFiles /Users/zarawasique/projects/PokemonCatalogue//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zarawasique/projects/PokemonCatalogue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PokemonCatalogue

# Build rule for target.
PokemonCatalogue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PokemonCatalogue
.PHONY : PokemonCatalogue

# fast build rule for target.
PokemonCatalogue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/build
.PHONY : PokemonCatalogue/fast

src/Catalogue.o: src/Catalogue.cpp.o
.PHONY : src/Catalogue.o

# target to build an object file
src/Catalogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Catalogue.cpp.o
.PHONY : src/Catalogue.cpp.o

src/Catalogue.i: src/Catalogue.cpp.i
.PHONY : src/Catalogue.i

# target to preprocess a source file
src/Catalogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Catalogue.cpp.i
.PHONY : src/Catalogue.cpp.i

src/Catalogue.s: src/Catalogue.cpp.s
.PHONY : src/Catalogue.s

# target to generate assembly for a file
src/Catalogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Catalogue.cpp.s
.PHONY : src/Catalogue.cpp.s

src/Pokemon.o: src/Pokemon.cpp.o
.PHONY : src/Pokemon.o

# target to build an object file
src/Pokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Pokemon.cpp.o
.PHONY : src/Pokemon.cpp.o

src/Pokemon.i: src/Pokemon.cpp.i
.PHONY : src/Pokemon.i

# target to preprocess a source file
src/Pokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Pokemon.cpp.i
.PHONY : src/Pokemon.cpp.i

src/Pokemon.s: src/Pokemon.cpp.s
.PHONY : src/Pokemon.s

# target to generate assembly for a file
src/Pokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/Pokemon.cpp.s
.PHONY : src/Pokemon.cpp.s

src/PokemonCatalogue.o: src/PokemonCatalogue.cpp.o
.PHONY : src/PokemonCatalogue.o

# target to build an object file
src/PokemonCatalogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/PokemonCatalogue.cpp.o
.PHONY : src/PokemonCatalogue.cpp.o

src/PokemonCatalogue.i: src/PokemonCatalogue.cpp.i
.PHONY : src/PokemonCatalogue.i

# target to preprocess a source file
src/PokemonCatalogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/PokemonCatalogue.cpp.i
.PHONY : src/PokemonCatalogue.cpp.i

src/PokemonCatalogue.s: src/PokemonCatalogue.cpp.s
.PHONY : src/PokemonCatalogue.s

# target to generate assembly for a file
src/PokemonCatalogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PokemonCatalogue.dir/build.make CMakeFiles/PokemonCatalogue.dir/src/PokemonCatalogue.cpp.s
.PHONY : src/PokemonCatalogue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PokemonCatalogue"
	@echo "... src/Catalogue.o"
	@echo "... src/Catalogue.i"
	@echo "... src/Catalogue.s"
	@echo "... src/Pokemon.o"
	@echo "... src/Pokemon.i"
	@echo "... src/Pokemon.s"
	@echo "... src/PokemonCatalogue.o"
	@echo "... src/PokemonCatalogue.i"
	@echo "... src/PokemonCatalogue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

