# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.8/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.8/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zarawasique/projects/PokemonCatalogue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zarawasique/projects/PokemonCatalogue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.8/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.8/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zarawasique/projects/PokemonCatalogue/CMakeFiles /Users/zarawasique/projects/PokemonCatalogue//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zarawasique/projects/PokemonCatalogue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pokemon

# Build rule for target.
Pokemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pokemon
.PHONY : Pokemon

# fast build rule for target.
Pokemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/build
.PHONY : Pokemon/fast

Catalogue.o: Catalogue.cpp.o
.PHONY : Catalogue.o

# target to build an object file
Catalogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Catalogue.cpp.o
.PHONY : Catalogue.cpp.o

Catalogue.i: Catalogue.cpp.i
.PHONY : Catalogue.i

# target to preprocess a source file
Catalogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Catalogue.cpp.i
.PHONY : Catalogue.cpp.i

Catalogue.s: Catalogue.cpp.s
.PHONY : Catalogue.s

# target to generate assembly for a file
Catalogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Catalogue.cpp.s
.PHONY : Catalogue.cpp.s

Pokemon.o: Pokemon.cpp.o
.PHONY : Pokemon.o

# target to build an object file
Pokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Pokemon.cpp.o
.PHONY : Pokemon.cpp.o

Pokemon.i: Pokemon.cpp.i
.PHONY : Pokemon.i

# target to preprocess a source file
Pokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Pokemon.cpp.i
.PHONY : Pokemon.cpp.i

Pokemon.s: Pokemon.cpp.s
.PHONY : Pokemon.s

# target to generate assembly for a file
Pokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/Pokemon.cpp.s
.PHONY : Pokemon.cpp.s

PokemonCatalogue.o: PokemonCatalogue.cpp.o
.PHONY : PokemonCatalogue.o

# target to build an object file
PokemonCatalogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/PokemonCatalogue.cpp.o
.PHONY : PokemonCatalogue.cpp.o

PokemonCatalogue.i: PokemonCatalogue.cpp.i
.PHONY : PokemonCatalogue.i

# target to preprocess a source file
PokemonCatalogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/PokemonCatalogue.cpp.i
.PHONY : PokemonCatalogue.cpp.i

PokemonCatalogue.s: PokemonCatalogue.cpp.s
.PHONY : PokemonCatalogue.s

# target to generate assembly for a file
PokemonCatalogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/PokemonCatalogue.cpp.s
.PHONY : PokemonCatalogue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pokemon"
	@echo "... Catalogue.o"
	@echo "... Catalogue.i"
	@echo "... Catalogue.s"
	@echo "... Pokemon.o"
	@echo "... Pokemon.i"
	@echo "... Pokemon.s"
	@echo "... PokemonCatalogue.o"
	@echo "... PokemonCatalogue.i"
	@echo "... PokemonCatalogue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

